stages:
  - package-plugin-for-engine
  - upload-plugin-for-engine
  - prepare-engine
  - build-plugin-for-engine
  - test-plugin-for-engine
  
include:
    - project: 'unreal-marketplace/pluginsdevops'
      ref: Live
      file: 
        - 'plugin-ci.yml'
        - 'plugin-cd.yml'
