// Copyright Out-of-the-Box Plugins 2018-2020. All Rights Reserved.

#include "BPNode_GenericVariablesBase.h"

#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"

#define LOCTEXT_NAMESPACE "VariablesSystemEditor"

namespace
{
	const FName InvaliadClassName = TEXT("INVALID_CLASS");
	const FName VariableOwnerTextPin = TEXT("VariableOwner");
	const FName VariableReferenceTextPin = TEXT("VariableToReference");
}

//////////////////////////////////////////////////////////////////////////
//UEdGraphNode implementation
void UBPNode_GenericVariablesBase::AllocateDefaultPins()
{
	// Create pin for Variable asset input
    CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UBaseVariable::StaticClass(), VariableReferenceTextPin);

	// Create pin for Variable owner
    UEdGraphPin* InVariableOwnerPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), VariableOwnerTextPin);
    InVariableOwnerPin->bAdvancedView = true;

	// Change only if unset.
    if (AdvancedPinDisplay == ENodeAdvancedPins::NoPins)
    {
        AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
    }

    Super::AllocateDefaultPins();
}

//////////////////////////////////////////////////////////////////////////
//K2Node implementation
void UBPNode_GenericVariablesBase::PostReconstructNode()
{
    Super::PostReconstructNode();

    UpdatePinTypeFromVariable();
}

void UBPNode_GenericVariablesBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
    Super::PinDefaultValueChanged(Pin);

	if (GetVariablePin() == Pin)
	{
		UpdatePinTypeFromVariable();
	}
}

void UBPNode_GenericVariablesBase::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
    Super::NotifyPinConnectionListChanged(Pin);

    if (GetVariablePin() == Pin)
    {
		UpdatePinTypeFromVariable();
    }
}

void UBPNode_GenericVariablesBase::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
    Super::ExpandNode(CompilerContext, SourceGraph);

    const FName VariableName = GetVariableNameToUse();
	
	if (CheckForCompilationErrors(VariableName, CompilerContext))
	{
		// If we have any compilation errors, just early return, the checks performed should log the source of the problem.
		return;
	}

	bool bSucceeded = true;

	if (UK2Node_CallFunction* CallCreateNode = CreateSpecificNode(VariableName, CompilerContext, SourceGraph))
	{
		// Instanced variables also have an owner, so we should connect that pin as well.
		if (IsInstancedVariable(VariableName))
		{
			UEdGraphPin* InputOwnerPin = GetVariableOwnerPin();
			UEdGraphPin* FunctioOwnerPin = CallCreateNode->FindPin(TEXT("owner"));
			bSucceeded &= InputOwnerPin && FunctioOwnerPin && CompilerContext.CopyPinLinksToIntermediate(*InputOwnerPin, *FunctioOwnerPin).CanSafeConnect();
		}

		// Connect Class pin.
		UEdGraphPin* ClassPin = GetVariablePin();
		UEdGraphPin* VariableInput = CallCreateNode->FindPin(TEXT("var"));
		bSucceeded &= ClassPin && VariableInput && CompilerContext.CopyPinLinksToIntermediate(*ClassPin, *VariableInput).CanSafeConnect();

		// Connect Result pin.
		UEdGraphPin* ResultPin = GetVariableValuePin();
		UEdGraphPin* ReturnPin = GetVariableLinkPin(CallCreateNode);
		bSucceeded &= ResultPin && ReturnPin && CompilerContext.MovePinLinksToIntermediate(*ResultPin, *ReturnPin).CanSafeConnect();

		// Class specific for Get/Set functionality.
		bSucceeded &= AdditionalExpand(CompilerContext, CallCreateNode);
	}
	else
	{
		bSucceeded = false;
	}

	if (!bSucceeded)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("K2NodeExpansionFailed", "[VariablesSystem] Failed to expand custom node.").ToString(), this);
	}
	
    BreakAllNodeLinks();
}

FText UBPNode_GenericVariablesBase::GetMenuCategory() const
{
	return LOCTEXT("GenericVariableBaseNode_MenuCategory", "VariablesSystem");
}

//////////////////////////////////////////////////////////////////////////
//Generated Methods
void UBPNode_GenericVariablesBase::UpdatePinTypeFromVariable()
{
    const FName VariableClassName = GetVariableNameToUse();

    FEdGraphPinType ResultPinType;
    EPinContainerType ResultContainerType = EPinContainerType::None;

	// This file is generated by the VariablesGenerator and should return the appropriate GraphPinType and PinContinaer types.
    #include "VariablesSystem/Generated/Node/PinTypeFromVariable.h"

    PropagatePinType(ResultPinType, ResultContainerType);
}

//////////////////////////////////////////////////////////////////////////
// Utility functionality
FName UBPNode_GenericVariablesBase::GetVariableNameToUse() const
{
    FName VariableClassName = InvaliadClassName;
	if (UEdGraphPin* ClassPin = GetVariablePin())
	{
		if (ClassPin->LinkedTo.Num() != 0 && ClassPin->LinkedTo[0])
		{
			VariableClassName = ClassPin->LinkedTo[0]->PinType.PinSubCategoryObject->GetFName();
		}
		else if (ClassPin->DefaultObject)
		{
			VariableClassName = ClassPin->DefaultObject->GetClass()->GetFName();
		}
	}

    return VariableClassName;
}

bool UBPNode_GenericVariablesBase::IsGlobalVariable(FName VariableName) const
{
	FString VariableClassString; VariableName.ToString(VariableClassString);
	return VariableClassString.Contains("Global");
}

bool UBPNode_GenericVariablesBase::IsInstancedVariable(FName VariableName) const
{
	FString VariableClassString; VariableName.ToString(VariableClassString);
	return VariableClassString.Contains("Instanced");
}

UEdGraphPin* UBPNode_GenericVariablesBase::GetVariablePin() const
{
	UEdGraphPin* Pin = FindPin(VariableReferenceTextPin);
	ensure(nullptr == Pin || Pin->Direction == EGPD_Input);
	return Pin;
}

UEdGraphPin* UBPNode_GenericVariablesBase::GetVariableOwnerPin() const
{
	UEdGraphPin* Pin = FindPin(VariableOwnerTextPin);
	ensure(nullptr == Pin || Pin->Direction == EGPD_Input);
	return Pin;
}

void UBPNode_GenericVariablesBase::PropagatePinType(FEdGraphPinType& InType, EPinContainerType containerType)
{
    const UClass* CallingContext = nullptr;
    if (UBlueprint const* Blueprint = GetBlueprint())
    {
		if (Blueprint->GeneratedClass)
		{
			CallingContext = Blueprint->GeneratedClass;
		}
		else
		{
			CallingContext = Blueprint->ParentClass;
		}
    }

    UEdGraphPin* ResultPin = GetVariableValuePin();

    ResultPin->PinType = InType;
    ResultPin->PinType.ContainerType = containerType;
	//TOSOLVE: Investigate this option.
    ResultPin->PinType.bIsReference = false;


    // Verify that all previous connections to this pin are still valid with the new type or break them.
    const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	for (const auto& ConnectedPin : ResultPin->LinkedTo)
	{
		if (!Schema->ArePinsCompatible(ResultPin, ConnectedPin, CallingContext))
		{
			ResultPin->BreakLinkTo(ConnectedPin);
		}
	}
}

bool UBPNode_GenericVariablesBase::CheckForCompilationErrors(FName VariableClassName, FKismetCompilerContext& CompilerContext) const
{
	enum class EGenericVariablesNodeError
	{
		None,
		UnkownType,
		GlobalHasOwner,
		InstancedMissingOwner,
	} Error = EGenericVariablesNodeError::None;

	const UEdGraphPin* OwnerPin = GetVariableOwnerPin();
	const bool bHasOwnerConnection = OwnerPin && (OwnerPin->DefaultObject || OwnerPin->LinkedTo.Num() > 0);

	const bool bIsGlobalVariable = IsGlobalVariable(VariableClassName);
	const bool bIsInstancedVariable = IsInstancedVariable(VariableClassName);

	if (!bIsGlobalVariable && !bIsInstancedVariable)
	{
		Error = EGenericVariablesNodeError::UnkownType;
	}
	else if (bIsGlobalVariable && bHasOwnerConnection)
	{
		Error = EGenericVariablesNodeError::GlobalHasOwner;
	}
	else if (bIsInstancedVariable && !bHasOwnerConnection)
	{
		Error = EGenericVariablesNodeError::InstancedMissingOwner;
	}

	switch (Error)
	{
		case EGenericVariablesNodeError::UnkownType:
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("CustomNodeFailedUnkown", "[VariablesSystem] Unkown function for variable type.").ToString(), this);

			break;
		}
		case EGenericVariablesNodeError::GlobalHasOwner:
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("CustomNodeFailedGlobalOwner", "[VariablesSystem] Global variables do not have a owner, please remove pin and/or value.").ToString(), this);

			break;
		}
		case EGenericVariablesNodeError::InstancedMissingOwner:
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("CustomNodeFailedInstancedOwner", "[VariablesSystem] Instanced variables must have an owner, please conect a pin or set a default value").ToString(), this);

			break;
		}
	}

	return Error != EGenericVariablesNodeError::None;
}

#undef LOCTEXT_NAMESPACE